spring:
  application:
    name: tvbingo
  datasource:
    url: ${TVBINGO_DB_URL}
    username: ${TVBINGO_DB_USERNAME}
    password: ${TVBINGO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: tvbingo_schema
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  output:
    ansi:
      enabled: ALWAYS
  ai:
    mcp:
      server:
        name: tvbingo-mcp-server
        version: 1.0.0
        type: SYNC
        stdio: true
        instructions: "This server provides TV Bingo tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%10.10t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: INFO
    com.tvbingo: DEBUG
    org.springframework.ai: DEBUG